### ISSUE TITLE
Status code 500. when sending newline character

### ISSUE THREAD

**Issue by Jebsta** [gajosu/whatsapp-ha-addon#19]
I send a message `Hallo\nDude!` to my phone.
With the `\n` it fails, without it not.

get a 500 status code

```
Logger: homeassistant.components.rest_command
Source: components/rest_command/__init__.py:136
Integration: RESTful Command ([documentation](https://www.home-assistant.io/integrations/rest_command), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+rest_command%22))
First occurred: 01:09:69 (3 occurrences)
Last logged: 01:11:53
Error. Url: http://homeassistant:3000/api/chats/XXXXXXXXXXXXX@c.us/messages. Status code 500. Payload: b'{"msg": "Hallo\nDude!"}'
```

**Comment by gajosu** [comment]
hello, could you show the addon logs?

**Comment by Jebsta** [comment]
```
8/6/2023, 17:25:08 [error]: 	Internal Server Error
SyntaxError: Unexpected token 
 in JSON at position 46
SyntaxError: Unexpected token
in JSON at position 46
  at JSON.parse (<anonymous>)
  at parse (/app/node_modules/body-parser/lib/types/json.js:89:19)
  at /app/node_modules/body-parser/lib/read.js:128:18
  at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
  at invokeCallback (/app/node_modules/raw-body/index.js:231:16)
  at done (/app/node_modules/raw-body/index.js:220:7)
  at IncomingMessage.onEnd (/app/node_modules/raw-body/index.js:280:7)
  at IncomingMessage.emit (events.js:412:35)
  at endReadableNT (internal/streams/readable.js:1333:12)
  at processTicksAndRejections (internal/process/task_queues.js:82:21)
The above error also had these properties on it:
{
  expose: true,
  statusCode: 400,
  status: 400,
  body: '{"msg": "This is a test message with linebreak\n' +
    '\n' +
    'This will fail to send but should not!"}',
  type: 'entity.parse.failed'
}
```
This is when I send it with a message with a js generated linebreak.
```js
msg.payload = `This is a test message with linebreak

This will fail to send but should not!`
```

**Comment by Jebsta** [comment]
I use Node-Red to Trigger the Service:
Here is my flow i use to replicate the error:
```json
[{"id":"92295325d7a59dad","type":"api-call-service","z":"fe3304dfc4c59cc6","name":"Send Whatsapp Message","server":"e181b42f.f4b2d8","version":5,"debugenabled":false,"domain":"rest_command","service":"whatsapp_send_text_message","areaId":[],"deviceId":[],"entityId":[],"data":"{\"message\": msg.answer ,\"chat_id\": msg.chat_id}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":850,"y":800,"wires":[[]]},{"id":"8d97b225cd6e4e35","type":"inject","z":"fe3304dfc4c59cc6","name":"Send Message","props":[{"p":"chat_id","v":"1234567890@c.us","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":200,"y":800,"wires":[["0a033585fec24f63"]]},{"id":"0a033585fec24f63","type":"function","z":"fe3304dfc4c59cc6","name":"Generate Message to send","func":"msg.answer = \"This is a test message with linebreak\\n\\nThis will fail to send but should not!\"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":500,"y":800,"wires":[["92295325d7a59dad"]]},{"id":"e181b42f.f4b2d8","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30,"areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"at: ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"h23","statusTimeFormat":"h:m","enableGlobalContextStore":true}]
```

**Comment by Jebsta** [comment]
A workaround on my side is to replace all `\n` with `\\n` but i don't know if it is intended behaviour

**Comment by gajosu** [comment]
After reviewing the error message you provided, it looks like the issue originates from the JSON string being sent.

Specifically, the newline characters (\n) within the JSON string need to be properly escaped. In JSON, special characters like newlines should be escaped as \\n. If they're not escaped properly, it can lead to an Unexpected token error, as we're seeing here.

In your case, the JSON should look like this:

```json
{
  "msg": "This is a test message with linebreak\\n\\nThis will fail to send but should not!"
}
```
If you're using Node-RED, you might find it useful to use JSON nodes for encoding your JSON or you could use a function node and call JSON.stringify() to ensure your JSON string is properly formatted.
