### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by mupsje** [gajosu/whatsapp-ha-addon#9]
hi, 

Is it possible to give some example how to put
images, url links, media , footers, etc...

Or do you have docs how to?

Maybe take a look at: 
https://github.com/giuseppecastaldo/ha-addons/blob/main/whatsapp_addon/DOCS.md

greets

**Comment by mupsje** [comment]
hi and thank you for your time,

Well I tried several options, getting only internal error 500...

Can you sent me a example how you do it from HA in Developer - Services ?
because I think i'm doing something wrong :)
or something is wrong with the web.js ....

text is working just fine.

ps, maybe it is also this problem...
https://github.com/pedroslopez/whatsapp-web.js/issues/2081

This is the error I get.


``` 
3/30/2023, 09:43:06 [error]: 	Internal Server Error
Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function
    at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)
    at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)
    at async __puppeteer_evaluation_script__:10:25
Error: Evaluation failed: TypeError: window.Store.MediaPrep.prepRawMedia is not a function
  at window.WWebJS.processMediaData (__puppeteer_evaluation_script__:235:50)
  at async window.WWebJS.sendMessage (__puppeteer_evaluation_script__:19:19)
  at async __puppeteer_evaluation_script__:10:25
  at ExecutionContext._evaluateInternal (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:95:5)
  at async ExecutionContext.evaluate (/app/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
  at async Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:686:28) 
```

**Comment by gajosu** [comment]
Hi, I have updated the version of the whatsapp-web.js library with this update the error you report should disappear
You should get a new version of this addon in supervisor
greets
